apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: 'agent-task-controller-{{ "VAULT" | env }}'
  namespace: '{{ "NAMESPACE" | env }}'
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
    keel.sh/pollSchedule: "@every 1m"
    random: '{{ "RANDOM" | env }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'agent-task-controller-{{ "VAULT" | env }}'
  serviceName: 'agent-task-controller-{{ "VAULT" | env }}'
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        random: '{{ "RANDOM" | env }}'
      labels:
        app: 'agent-task-controller-{{ "VAULT" | env }}'
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node_type
                    operator: In
                    values:
                      - '{{ "NAMESPACE" | env }}'
      containers:
        - name: service
          args:
            - -v={{"LOGLEVEL" | env}}
          env:
            - name: LISTEN
              value: ':9090'
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  key: sentry-dsn
                  name: 'agent-task-controller-{{ "VAULT" | env }}'
            - name: GATEWAY_SECRET
              valueFrom:
                secretKeyRef:
                  key: gateway-secret
                  name: 'agent-task-controller-{{ "VAULT" | env }}'
            - name: SENTRY_PROXY
              value: '{{"SENTRY_PROXY_URL" | env}}'
            - name: BRANCH
              value: '{{ "BRANCH" | env }}'
            - name: KAFKA_BROKERS
              value: '{{ "KAFKA_BROKERS" | env }}'
            - name: GIT_REST_URL
              value: 'http://vault-obsidian-{{ "VAULT" | env }}:9090'
            - name: VAULT_NAME
              value: '{{ "VAULT" | env }}'
            - name: POLL_INTERVAL
              value: '60s'
            - name: TASK_DIR
              value: '{{ "TASK_DIR" | env }}'
            - name: DATA_DIR
              value: /data/bolt
            - name: NO_SYNC
              value: "false"
            - name: AUTO_INJECT_TASK_IDENTIFIER
              value: '{{ "AUTO_INJECT_TASK_IDENTIFIER" | env }}'
          image: '{{"DOCKER_REGISTRY" | env}}/agent-task-controller:{{"BRANCH" | env}}'
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          ports:
            - containerPort: 9090
              name: http
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 50Mi
            requests:
              cpu: 20m
              memory: 20Mi
          volumeMounts:
            - mountPath: /data
              name: datadir
      imagePullSecrets:
        - name: docker
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
