// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/task/controller/pkg/gitrestclient"
)

type GitClient struct {
	AtomicReadModifyWriteAndCommitPushStub        func(context.Context, string, func(current []byte) ([]byte, error), string) error
	atomicReadModifyWriteAndCommitPushMutex       sync.RWMutex
	atomicReadModifyWriteAndCommitPushArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 func(current []byte) ([]byte, error)
		arg4 string
	}
	atomicReadModifyWriteAndCommitPushReturns struct {
		result1 error
	}
	atomicReadModifyWriteAndCommitPushReturnsOnCall map[int]struct {
		result1 error
	}
	AtomicWriteAndCommitPushStub        func(context.Context, string, []byte, string) error
	atomicWriteAndCommitPushMutex       sync.RWMutex
	atomicWriteAndCommitPushArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []byte
		arg4 string
	}
	atomicWriteAndCommitPushReturns struct {
		result1 error
	}
	atomicWriteAndCommitPushReturnsOnCall map[int]struct {
		result1 error
	}
	CommitAndPushStub        func(context.Context, string) error
	commitAndPushMutex       sync.RWMutex
	commitAndPushArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	commitAndPushReturns struct {
		result1 error
	}
	commitAndPushReturnsOnCall map[int]struct {
		result1 error
	}
	EnsureClonedStub        func(context.Context) error
	ensureClonedMutex       sync.RWMutex
	ensureClonedArgsForCall []struct {
		arg1 context.Context
	}
	ensureClonedReturns struct {
		result1 error
	}
	ensureClonedReturnsOnCall map[int]struct {
		result1 error
	}
	ListFilesStub        func(context.Context, string) ([]string, error)
	listFilesMutex       sync.RWMutex
	listFilesArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	listFilesReturns struct {
		result1 []string
		result2 error
	}
	listFilesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	PathStub        func() string
	pathMutex       sync.RWMutex
	pathArgsForCall []struct {
	}
	pathReturns struct {
		result1 string
	}
	pathReturnsOnCall map[int]struct {
		result1 string
	}
	PullStub        func(context.Context) error
	pullMutex       sync.RWMutex
	pullArgsForCall []struct {
		arg1 context.Context
	}
	pullReturns struct {
		result1 error
	}
	pullReturnsOnCall map[int]struct {
		result1 error
	}
	ReadFileStub        func(context.Context, string) ([]byte, error)
	readFileMutex       sync.RWMutex
	readFileArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	readFileReturns struct {
		result1 []byte
		result2 error
	}
	readFileReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	WriteFileStub        func(context.Context, string, []byte) error
	writeFileMutex       sync.RWMutex
	writeFileArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []byte
	}
	writeFileReturns struct {
		result1 error
	}
	writeFileReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GitClient) AtomicReadModifyWriteAndCommitPush(arg1 context.Context, arg2 string, arg3 func(current []byte) ([]byte, error), arg4 string) error {
	fake.atomicReadModifyWriteAndCommitPushMutex.Lock()
	ret, specificReturn := fake.atomicReadModifyWriteAndCommitPushReturnsOnCall[len(fake.atomicReadModifyWriteAndCommitPushArgsForCall)]
	fake.atomicReadModifyWriteAndCommitPushArgsForCall = append(fake.atomicReadModifyWriteAndCommitPushArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 func(current []byte) ([]byte, error)
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.AtomicReadModifyWriteAndCommitPushStub
	fakeReturns := fake.atomicReadModifyWriteAndCommitPushReturns
	fake.recordInvocation("AtomicReadModifyWriteAndCommitPush", []interface{}{arg1, arg2, arg3, arg4})
	fake.atomicReadModifyWriteAndCommitPushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitClient) AtomicReadModifyWriteAndCommitPushCallCount() int {
	fake.atomicReadModifyWriteAndCommitPushMutex.RLock()
	defer fake.atomicReadModifyWriteAndCommitPushMutex.RUnlock()
	return len(fake.atomicReadModifyWriteAndCommitPushArgsForCall)
}

func (fake *GitClient) AtomicReadModifyWriteAndCommitPushCalls(stub func(context.Context, string, func(current []byte) ([]byte, error), string) error) {
	fake.atomicReadModifyWriteAndCommitPushMutex.Lock()
	defer fake.atomicReadModifyWriteAndCommitPushMutex.Unlock()
	fake.AtomicReadModifyWriteAndCommitPushStub = stub
}

func (fake *GitClient) AtomicReadModifyWriteAndCommitPushArgsForCall(i int) (context.Context, string, func(current []byte) ([]byte, error), string) {
	fake.atomicReadModifyWriteAndCommitPushMutex.RLock()
	defer fake.atomicReadModifyWriteAndCommitPushMutex.RUnlock()
	argsForCall := fake.atomicReadModifyWriteAndCommitPushArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitClient) AtomicReadModifyWriteAndCommitPushReturns(result1 error) {
	fake.atomicReadModifyWriteAndCommitPushMutex.Lock()
	defer fake.atomicReadModifyWriteAndCommitPushMutex.Unlock()
	fake.AtomicReadModifyWriteAndCommitPushStub = nil
	fake.atomicReadModifyWriteAndCommitPushReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitClient) AtomicReadModifyWriteAndCommitPushReturnsOnCall(i int, result1 error) {
	fake.atomicReadModifyWriteAndCommitPushMutex.Lock()
	defer fake.atomicReadModifyWriteAndCommitPushMutex.Unlock()
	fake.AtomicReadModifyWriteAndCommitPushStub = nil
	if fake.atomicReadModifyWriteAndCommitPushReturnsOnCall == nil {
		fake.atomicReadModifyWriteAndCommitPushReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.atomicReadModifyWriteAndCommitPushReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitClient) AtomicWriteAndCommitPush(arg1 context.Context, arg2 string, arg3 []byte, arg4 string) error {
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.atomicWriteAndCommitPushMutex.Lock()
	ret, specificReturn := fake.atomicWriteAndCommitPushReturnsOnCall[len(fake.atomicWriteAndCommitPushArgsForCall)]
	fake.atomicWriteAndCommitPushArgsForCall = append(fake.atomicWriteAndCommitPushArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []byte
		arg4 string
	}{arg1, arg2, arg3Copy, arg4})
	stub := fake.AtomicWriteAndCommitPushStub
	fakeReturns := fake.atomicWriteAndCommitPushReturns
	fake.recordInvocation("AtomicWriteAndCommitPush", []interface{}{arg1, arg2, arg3Copy, arg4})
	fake.atomicWriteAndCommitPushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitClient) AtomicWriteAndCommitPushCallCount() int {
	fake.atomicWriteAndCommitPushMutex.RLock()
	defer fake.atomicWriteAndCommitPushMutex.RUnlock()
	return len(fake.atomicWriteAndCommitPushArgsForCall)
}

func (fake *GitClient) AtomicWriteAndCommitPushCalls(stub func(context.Context, string, []byte, string) error) {
	fake.atomicWriteAndCommitPushMutex.Lock()
	defer fake.atomicWriteAndCommitPushMutex.Unlock()
	fake.AtomicWriteAndCommitPushStub = stub
}

func (fake *GitClient) AtomicWriteAndCommitPushArgsForCall(i int) (context.Context, string, []byte, string) {
	fake.atomicWriteAndCommitPushMutex.RLock()
	defer fake.atomicWriteAndCommitPushMutex.RUnlock()
	argsForCall := fake.atomicWriteAndCommitPushArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitClient) AtomicWriteAndCommitPushReturns(result1 error) {
	fake.atomicWriteAndCommitPushMutex.Lock()
	defer fake.atomicWriteAndCommitPushMutex.Unlock()
	fake.AtomicWriteAndCommitPushStub = nil
	fake.atomicWriteAndCommitPushReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitClient) AtomicWriteAndCommitPushReturnsOnCall(i int, result1 error) {
	fake.atomicWriteAndCommitPushMutex.Lock()
	defer fake.atomicWriteAndCommitPushMutex.Unlock()
	fake.AtomicWriteAndCommitPushStub = nil
	if fake.atomicWriteAndCommitPushReturnsOnCall == nil {
		fake.atomicWriteAndCommitPushReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.atomicWriteAndCommitPushReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitClient) CommitAndPush(arg1 context.Context, arg2 string) error {
	fake.commitAndPushMutex.Lock()
	ret, specificReturn := fake.commitAndPushReturnsOnCall[len(fake.commitAndPushArgsForCall)]
	fake.commitAndPushArgsForCall = append(fake.commitAndPushArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.CommitAndPushStub
	fakeReturns := fake.commitAndPushReturns
	fake.recordInvocation("CommitAndPush", []interface{}{arg1, arg2})
	fake.commitAndPushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitClient) CommitAndPushCallCount() int {
	fake.commitAndPushMutex.RLock()
	defer fake.commitAndPushMutex.RUnlock()
	return len(fake.commitAndPushArgsForCall)
}

func (fake *GitClient) CommitAndPushCalls(stub func(context.Context, string) error) {
	fake.commitAndPushMutex.Lock()
	defer fake.commitAndPushMutex.Unlock()
	fake.CommitAndPushStub = stub
}

func (fake *GitClient) CommitAndPushArgsForCall(i int) (context.Context, string) {
	fake.commitAndPushMutex.RLock()
	defer fake.commitAndPushMutex.RUnlock()
	argsForCall := fake.commitAndPushArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GitClient) CommitAndPushReturns(result1 error) {
	fake.commitAndPushMutex.Lock()
	defer fake.commitAndPushMutex.Unlock()
	fake.CommitAndPushStub = nil
	fake.commitAndPushReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitClient) CommitAndPushReturnsOnCall(i int, result1 error) {
	fake.commitAndPushMutex.Lock()
	defer fake.commitAndPushMutex.Unlock()
	fake.CommitAndPushStub = nil
	if fake.commitAndPushReturnsOnCall == nil {
		fake.commitAndPushReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.commitAndPushReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitClient) EnsureCloned(arg1 context.Context) error {
	fake.ensureClonedMutex.Lock()
	ret, specificReturn := fake.ensureClonedReturnsOnCall[len(fake.ensureClonedArgsForCall)]
	fake.ensureClonedArgsForCall = append(fake.ensureClonedArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.EnsureClonedStub
	fakeReturns := fake.ensureClonedReturns
	fake.recordInvocation("EnsureCloned", []interface{}{arg1})
	fake.ensureClonedMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitClient) EnsureClonedCallCount() int {
	fake.ensureClonedMutex.RLock()
	defer fake.ensureClonedMutex.RUnlock()
	return len(fake.ensureClonedArgsForCall)
}

func (fake *GitClient) EnsureClonedCalls(stub func(context.Context) error) {
	fake.ensureClonedMutex.Lock()
	defer fake.ensureClonedMutex.Unlock()
	fake.EnsureClonedStub = stub
}

func (fake *GitClient) EnsureClonedArgsForCall(i int) context.Context {
	fake.ensureClonedMutex.RLock()
	defer fake.ensureClonedMutex.RUnlock()
	argsForCall := fake.ensureClonedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *GitClient) EnsureClonedReturns(result1 error) {
	fake.ensureClonedMutex.Lock()
	defer fake.ensureClonedMutex.Unlock()
	fake.EnsureClonedStub = nil
	fake.ensureClonedReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitClient) EnsureClonedReturnsOnCall(i int, result1 error) {
	fake.ensureClonedMutex.Lock()
	defer fake.ensureClonedMutex.Unlock()
	fake.EnsureClonedStub = nil
	if fake.ensureClonedReturnsOnCall == nil {
		fake.ensureClonedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.ensureClonedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitClient) ListFiles(arg1 context.Context, arg2 string) ([]string, error) {
	fake.listFilesMutex.Lock()
	ret, specificReturn := fake.listFilesReturnsOnCall[len(fake.listFilesArgsForCall)]
	fake.listFilesArgsForCall = append(fake.listFilesArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ListFilesStub
	fakeReturns := fake.listFilesReturns
	fake.recordInvocation("ListFiles", []interface{}{arg1, arg2})
	fake.listFilesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitClient) ListFilesCallCount() int {
	fake.listFilesMutex.RLock()
	defer fake.listFilesMutex.RUnlock()
	return len(fake.listFilesArgsForCall)
}

func (fake *GitClient) ListFilesCalls(stub func(context.Context, string) ([]string, error)) {
	fake.listFilesMutex.Lock()
	defer fake.listFilesMutex.Unlock()
	fake.ListFilesStub = stub
}

func (fake *GitClient) ListFilesArgsForCall(i int) (context.Context, string) {
	fake.listFilesMutex.RLock()
	defer fake.listFilesMutex.RUnlock()
	argsForCall := fake.listFilesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GitClient) ListFilesReturns(result1 []string, result2 error) {
	fake.listFilesMutex.Lock()
	defer fake.listFilesMutex.Unlock()
	fake.ListFilesStub = nil
	fake.listFilesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitClient) ListFilesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.listFilesMutex.Lock()
	defer fake.listFilesMutex.Unlock()
	fake.ListFilesStub = nil
	if fake.listFilesReturnsOnCall == nil {
		fake.listFilesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.listFilesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *GitClient) Path() string {
	fake.pathMutex.Lock()
	ret, specificReturn := fake.pathReturnsOnCall[len(fake.pathArgsForCall)]
	fake.pathArgsForCall = append(fake.pathArgsForCall, struct {
	}{})
	stub := fake.PathStub
	fakeReturns := fake.pathReturns
	fake.recordInvocation("Path", []interface{}{})
	fake.pathMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitClient) PathCallCount() int {
	fake.pathMutex.RLock()
	defer fake.pathMutex.RUnlock()
	return len(fake.pathArgsForCall)
}

func (fake *GitClient) PathCalls(stub func() string) {
	fake.pathMutex.Lock()
	defer fake.pathMutex.Unlock()
	fake.PathStub = stub
}

func (fake *GitClient) PathReturns(result1 string) {
	fake.pathMutex.Lock()
	defer fake.pathMutex.Unlock()
	fake.PathStub = nil
	fake.pathReturns = struct {
		result1 string
	}{result1}
}

func (fake *GitClient) PathReturnsOnCall(i int, result1 string) {
	fake.pathMutex.Lock()
	defer fake.pathMutex.Unlock()
	fake.PathStub = nil
	if fake.pathReturnsOnCall == nil {
		fake.pathReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.pathReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *GitClient) Pull(arg1 context.Context) error {
	fake.pullMutex.Lock()
	ret, specificReturn := fake.pullReturnsOnCall[len(fake.pullArgsForCall)]
	fake.pullArgsForCall = append(fake.pullArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.PullStub
	fakeReturns := fake.pullReturns
	fake.recordInvocation("Pull", []interface{}{arg1})
	fake.pullMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitClient) PullCallCount() int {
	fake.pullMutex.RLock()
	defer fake.pullMutex.RUnlock()
	return len(fake.pullArgsForCall)
}

func (fake *GitClient) PullCalls(stub func(context.Context) error) {
	fake.pullMutex.Lock()
	defer fake.pullMutex.Unlock()
	fake.PullStub = stub
}

func (fake *GitClient) PullArgsForCall(i int) context.Context {
	fake.pullMutex.RLock()
	defer fake.pullMutex.RUnlock()
	argsForCall := fake.pullArgsForCall[i]
	return argsForCall.arg1
}

func (fake *GitClient) PullReturns(result1 error) {
	fake.pullMutex.Lock()
	defer fake.pullMutex.Unlock()
	fake.PullStub = nil
	fake.pullReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitClient) PullReturnsOnCall(i int, result1 error) {
	fake.pullMutex.Lock()
	defer fake.pullMutex.Unlock()
	fake.PullStub = nil
	if fake.pullReturnsOnCall == nil {
		fake.pullReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pullReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitClient) ReadFile(arg1 context.Context, arg2 string) ([]byte, error) {
	fake.readFileMutex.Lock()
	ret, specificReturn := fake.readFileReturnsOnCall[len(fake.readFileArgsForCall)]
	fake.readFileArgsForCall = append(fake.readFileArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ReadFileStub
	fakeReturns := fake.readFileReturns
	fake.recordInvocation("ReadFile", []interface{}{arg1, arg2})
	fake.readFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitClient) ReadFileCallCount() int {
	fake.readFileMutex.RLock()
	defer fake.readFileMutex.RUnlock()
	return len(fake.readFileArgsForCall)
}

func (fake *GitClient) ReadFileCalls(stub func(context.Context, string) ([]byte, error)) {
	fake.readFileMutex.Lock()
	defer fake.readFileMutex.Unlock()
	fake.ReadFileStub = stub
}

func (fake *GitClient) ReadFileArgsForCall(i int) (context.Context, string) {
	fake.readFileMutex.RLock()
	defer fake.readFileMutex.RUnlock()
	argsForCall := fake.readFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GitClient) ReadFileReturns(result1 []byte, result2 error) {
	fake.readFileMutex.Lock()
	defer fake.readFileMutex.Unlock()
	fake.ReadFileStub = nil
	fake.readFileReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *GitClient) ReadFileReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.readFileMutex.Lock()
	defer fake.readFileMutex.Unlock()
	fake.ReadFileStub = nil
	if fake.readFileReturnsOnCall == nil {
		fake.readFileReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.readFileReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *GitClient) WriteFile(arg1 context.Context, arg2 string, arg3 []byte) error {
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.writeFileMutex.Lock()
	ret, specificReturn := fake.writeFileReturnsOnCall[len(fake.writeFileArgsForCall)]
	fake.writeFileArgsForCall = append(fake.writeFileArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []byte
	}{arg1, arg2, arg3Copy})
	stub := fake.WriteFileStub
	fakeReturns := fake.writeFileReturns
	fake.recordInvocation("WriteFile", []interface{}{arg1, arg2, arg3Copy})
	fake.writeFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitClient) WriteFileCallCount() int {
	fake.writeFileMutex.RLock()
	defer fake.writeFileMutex.RUnlock()
	return len(fake.writeFileArgsForCall)
}

func (fake *GitClient) WriteFileCalls(stub func(context.Context, string, []byte) error) {
	fake.writeFileMutex.Lock()
	defer fake.writeFileMutex.Unlock()
	fake.WriteFileStub = stub
}

func (fake *GitClient) WriteFileArgsForCall(i int) (context.Context, string, []byte) {
	fake.writeFileMutex.RLock()
	defer fake.writeFileMutex.RUnlock()
	argsForCall := fake.writeFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *GitClient) WriteFileReturns(result1 error) {
	fake.writeFileMutex.Lock()
	defer fake.writeFileMutex.Unlock()
	fake.WriteFileStub = nil
	fake.writeFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitClient) WriteFileReturnsOnCall(i int, result1 error) {
	fake.writeFileMutex.Lock()
	defer fake.writeFileMutex.Unlock()
	fake.WriteFileStub = nil
	if fake.writeFileReturnsOnCall == nil {
		fake.writeFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GitClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ gitrestclient.GitClient = new(GitClient)
