// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/agent-task-controller/pkg/metrics"
	"github.com/prometheus/client_golang/prometheus"
)

type Metrics struct {
	ConflictResolutionsTotalStub        func() prometheus.Counter
	conflictResolutionsTotalMutex       sync.RWMutex
	conflictResolutionsTotalArgsForCall []struct {
	}
	conflictResolutionsTotalReturns struct {
		result1 prometheus.Counter
	}
	conflictResolutionsTotalReturnsOnCall map[int]struct {
		result1 prometheus.Counter
	}
	FrontmatterCommandsTotalStub        func(string, string) prometheus.Counter
	frontmatterCommandsTotalMutex       sync.RWMutex
	frontmatterCommandsTotalArgsForCall []struct {
		arg1 string
		arg2 string
	}
	frontmatterCommandsTotalReturns struct {
		result1 prometheus.Counter
	}
	frontmatterCommandsTotalReturnsOnCall map[int]struct {
		result1 prometheus.Counter
	}
	GitPushTotalStub        func(string) prometheus.Counter
	gitPushTotalMutex       sync.RWMutex
	gitPushTotalArgsForCall []struct {
		arg1 string
	}
	gitPushTotalReturns struct {
		result1 prometheus.Counter
	}
	gitPushTotalReturnsOnCall map[int]struct {
		result1 prometheus.Counter
	}
	GitRestCallsTotalStub        func(string, string) prometheus.Counter
	gitRestCallsTotalMutex       sync.RWMutex
	gitRestCallsTotalArgsForCall []struct {
		arg1 string
		arg2 string
	}
	gitRestCallsTotalReturns struct {
		result1 prometheus.Counter
	}
	gitRestCallsTotalReturnsOnCall map[int]struct {
		result1 prometheus.Counter
	}
	KafkaConsumePausedTotalStub        func() prometheus.Counter
	kafkaConsumePausedTotalMutex       sync.RWMutex
	kafkaConsumePausedTotalArgsForCall []struct {
	}
	kafkaConsumePausedTotalReturns struct {
		result1 prometheus.Counter
	}
	kafkaConsumePausedTotalReturnsOnCall map[int]struct {
		result1 prometheus.Counter
	}
	PlanningRetryTotalStub        func(string) prometheus.Counter
	planningRetryTotalMutex       sync.RWMutex
	planningRetryTotalArgsForCall []struct {
		arg1 string
	}
	planningRetryTotalReturns struct {
		result1 prometheus.Counter
	}
	planningRetryTotalReturnsOnCall map[int]struct {
		result1 prometheus.Counter
	}
	ResultsWrittenTotalStub        func(string) prometheus.Counter
	resultsWrittenTotalMutex       sync.RWMutex
	resultsWrittenTotalArgsForCall []struct {
		arg1 string
	}
	resultsWrittenTotalReturns struct {
		result1 prometheus.Counter
	}
	resultsWrittenTotalReturnsOnCall map[int]struct {
		result1 prometheus.Counter
	}
	ScanCyclesTotalStub        func(string) prometheus.Counter
	scanCyclesTotalMutex       sync.RWMutex
	scanCyclesTotalArgsForCall []struct {
		arg1 string
	}
	scanCyclesTotalReturns struct {
		result1 prometheus.Counter
	}
	scanCyclesTotalReturnsOnCall map[int]struct {
		result1 prometheus.Counter
	}
	SkippedFilesTotalStub        func(metrics.SkipReason) prometheus.Counter
	skippedFilesTotalMutex       sync.RWMutex
	skippedFilesTotalArgsForCall []struct {
		arg1 metrics.SkipReason
	}
	skippedFilesTotalReturns struct {
		result1 prometheus.Counter
	}
	skippedFilesTotalReturnsOnCall map[int]struct {
		result1 prometheus.Counter
	}
	TasksPublishedTotalStub        func(string) prometheus.Counter
	tasksPublishedTotalMutex       sync.RWMutex
	tasksPublishedTotalArgsForCall []struct {
		arg1 string
	}
	tasksPublishedTotalReturns struct {
		result1 prometheus.Counter
	}
	tasksPublishedTotalReturnsOnCall map[int]struct {
		result1 prometheus.Counter
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Metrics) ConflictResolutionsTotal() prometheus.Counter {
	fake.conflictResolutionsTotalMutex.Lock()
	ret, specificReturn := fake.conflictResolutionsTotalReturnsOnCall[len(fake.conflictResolutionsTotalArgsForCall)]
	fake.conflictResolutionsTotalArgsForCall = append(fake.conflictResolutionsTotalArgsForCall, struct {
	}{})
	stub := fake.ConflictResolutionsTotalStub
	fakeReturns := fake.conflictResolutionsTotalReturns
	fake.recordInvocation("ConflictResolutionsTotal", []interface{}{})
	fake.conflictResolutionsTotalMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Metrics) ConflictResolutionsTotalCallCount() int {
	fake.conflictResolutionsTotalMutex.RLock()
	defer fake.conflictResolutionsTotalMutex.RUnlock()
	return len(fake.conflictResolutionsTotalArgsForCall)
}

func (fake *Metrics) ConflictResolutionsTotalCalls(stub func() prometheus.Counter) {
	fake.conflictResolutionsTotalMutex.Lock()
	defer fake.conflictResolutionsTotalMutex.Unlock()
	fake.ConflictResolutionsTotalStub = stub
}

func (fake *Metrics) ConflictResolutionsTotalReturns(result1 prometheus.Counter) {
	fake.conflictResolutionsTotalMutex.Lock()
	defer fake.conflictResolutionsTotalMutex.Unlock()
	fake.ConflictResolutionsTotalStub = nil
	fake.conflictResolutionsTotalReturns = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) ConflictResolutionsTotalReturnsOnCall(i int, result1 prometheus.Counter) {
	fake.conflictResolutionsTotalMutex.Lock()
	defer fake.conflictResolutionsTotalMutex.Unlock()
	fake.ConflictResolutionsTotalStub = nil
	if fake.conflictResolutionsTotalReturnsOnCall == nil {
		fake.conflictResolutionsTotalReturnsOnCall = make(map[int]struct {
			result1 prometheus.Counter
		})
	}
	fake.conflictResolutionsTotalReturnsOnCall[i] = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) FrontmatterCommandsTotal(arg1 string, arg2 string) prometheus.Counter {
	fake.frontmatterCommandsTotalMutex.Lock()
	ret, specificReturn := fake.frontmatterCommandsTotalReturnsOnCall[len(fake.frontmatterCommandsTotalArgsForCall)]
	fake.frontmatterCommandsTotalArgsForCall = append(fake.frontmatterCommandsTotalArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.FrontmatterCommandsTotalStub
	fakeReturns := fake.frontmatterCommandsTotalReturns
	fake.recordInvocation("FrontmatterCommandsTotal", []interface{}{arg1, arg2})
	fake.frontmatterCommandsTotalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Metrics) FrontmatterCommandsTotalCallCount() int {
	fake.frontmatterCommandsTotalMutex.RLock()
	defer fake.frontmatterCommandsTotalMutex.RUnlock()
	return len(fake.frontmatterCommandsTotalArgsForCall)
}

func (fake *Metrics) FrontmatterCommandsTotalCalls(stub func(string, string) prometheus.Counter) {
	fake.frontmatterCommandsTotalMutex.Lock()
	defer fake.frontmatterCommandsTotalMutex.Unlock()
	fake.FrontmatterCommandsTotalStub = stub
}

func (fake *Metrics) FrontmatterCommandsTotalArgsForCall(i int) (string, string) {
	fake.frontmatterCommandsTotalMutex.RLock()
	defer fake.frontmatterCommandsTotalMutex.RUnlock()
	argsForCall := fake.frontmatterCommandsTotalArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Metrics) FrontmatterCommandsTotalReturns(result1 prometheus.Counter) {
	fake.frontmatterCommandsTotalMutex.Lock()
	defer fake.frontmatterCommandsTotalMutex.Unlock()
	fake.FrontmatterCommandsTotalStub = nil
	fake.frontmatterCommandsTotalReturns = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) FrontmatterCommandsTotalReturnsOnCall(i int, result1 prometheus.Counter) {
	fake.frontmatterCommandsTotalMutex.Lock()
	defer fake.frontmatterCommandsTotalMutex.Unlock()
	fake.FrontmatterCommandsTotalStub = nil
	if fake.frontmatterCommandsTotalReturnsOnCall == nil {
		fake.frontmatterCommandsTotalReturnsOnCall = make(map[int]struct {
			result1 prometheus.Counter
		})
	}
	fake.frontmatterCommandsTotalReturnsOnCall[i] = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) GitPushTotal(arg1 string) prometheus.Counter {
	fake.gitPushTotalMutex.Lock()
	ret, specificReturn := fake.gitPushTotalReturnsOnCall[len(fake.gitPushTotalArgsForCall)]
	fake.gitPushTotalArgsForCall = append(fake.gitPushTotalArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GitPushTotalStub
	fakeReturns := fake.gitPushTotalReturns
	fake.recordInvocation("GitPushTotal", []interface{}{arg1})
	fake.gitPushTotalMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Metrics) GitPushTotalCallCount() int {
	fake.gitPushTotalMutex.RLock()
	defer fake.gitPushTotalMutex.RUnlock()
	return len(fake.gitPushTotalArgsForCall)
}

func (fake *Metrics) GitPushTotalCalls(stub func(string) prometheus.Counter) {
	fake.gitPushTotalMutex.Lock()
	defer fake.gitPushTotalMutex.Unlock()
	fake.GitPushTotalStub = stub
}

func (fake *Metrics) GitPushTotalArgsForCall(i int) string {
	fake.gitPushTotalMutex.RLock()
	defer fake.gitPushTotalMutex.RUnlock()
	argsForCall := fake.gitPushTotalArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) GitPushTotalReturns(result1 prometheus.Counter) {
	fake.gitPushTotalMutex.Lock()
	defer fake.gitPushTotalMutex.Unlock()
	fake.GitPushTotalStub = nil
	fake.gitPushTotalReturns = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) GitPushTotalReturnsOnCall(i int, result1 prometheus.Counter) {
	fake.gitPushTotalMutex.Lock()
	defer fake.gitPushTotalMutex.Unlock()
	fake.GitPushTotalStub = nil
	if fake.gitPushTotalReturnsOnCall == nil {
		fake.gitPushTotalReturnsOnCall = make(map[int]struct {
			result1 prometheus.Counter
		})
	}
	fake.gitPushTotalReturnsOnCall[i] = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) GitRestCallsTotal(arg1 string, arg2 string) prometheus.Counter {
	fake.gitRestCallsTotalMutex.Lock()
	ret, specificReturn := fake.gitRestCallsTotalReturnsOnCall[len(fake.gitRestCallsTotalArgsForCall)]
	fake.gitRestCallsTotalArgsForCall = append(fake.gitRestCallsTotalArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.GitRestCallsTotalStub
	fakeReturns := fake.gitRestCallsTotalReturns
	fake.recordInvocation("GitRestCallsTotal", []interface{}{arg1, arg2})
	fake.gitRestCallsTotalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Metrics) GitRestCallsTotalCallCount() int {
	fake.gitRestCallsTotalMutex.RLock()
	defer fake.gitRestCallsTotalMutex.RUnlock()
	return len(fake.gitRestCallsTotalArgsForCall)
}

func (fake *Metrics) GitRestCallsTotalCalls(stub func(string, string) prometheus.Counter) {
	fake.gitRestCallsTotalMutex.Lock()
	defer fake.gitRestCallsTotalMutex.Unlock()
	fake.GitRestCallsTotalStub = stub
}

func (fake *Metrics) GitRestCallsTotalArgsForCall(i int) (string, string) {
	fake.gitRestCallsTotalMutex.RLock()
	defer fake.gitRestCallsTotalMutex.RUnlock()
	argsForCall := fake.gitRestCallsTotalArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Metrics) GitRestCallsTotalReturns(result1 prometheus.Counter) {
	fake.gitRestCallsTotalMutex.Lock()
	defer fake.gitRestCallsTotalMutex.Unlock()
	fake.GitRestCallsTotalStub = nil
	fake.gitRestCallsTotalReturns = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) GitRestCallsTotalReturnsOnCall(i int, result1 prometheus.Counter) {
	fake.gitRestCallsTotalMutex.Lock()
	defer fake.gitRestCallsTotalMutex.Unlock()
	fake.GitRestCallsTotalStub = nil
	if fake.gitRestCallsTotalReturnsOnCall == nil {
		fake.gitRestCallsTotalReturnsOnCall = make(map[int]struct {
			result1 prometheus.Counter
		})
	}
	fake.gitRestCallsTotalReturnsOnCall[i] = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) KafkaConsumePausedTotal() prometheus.Counter {
	fake.kafkaConsumePausedTotalMutex.Lock()
	ret, specificReturn := fake.kafkaConsumePausedTotalReturnsOnCall[len(fake.kafkaConsumePausedTotalArgsForCall)]
	fake.kafkaConsumePausedTotalArgsForCall = append(fake.kafkaConsumePausedTotalArgsForCall, struct {
	}{})
	stub := fake.KafkaConsumePausedTotalStub
	fakeReturns := fake.kafkaConsumePausedTotalReturns
	fake.recordInvocation("KafkaConsumePausedTotal", []interface{}{})
	fake.kafkaConsumePausedTotalMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Metrics) KafkaConsumePausedTotalCallCount() int {
	fake.kafkaConsumePausedTotalMutex.RLock()
	defer fake.kafkaConsumePausedTotalMutex.RUnlock()
	return len(fake.kafkaConsumePausedTotalArgsForCall)
}

func (fake *Metrics) KafkaConsumePausedTotalCalls(stub func() prometheus.Counter) {
	fake.kafkaConsumePausedTotalMutex.Lock()
	defer fake.kafkaConsumePausedTotalMutex.Unlock()
	fake.KafkaConsumePausedTotalStub = stub
}

func (fake *Metrics) KafkaConsumePausedTotalReturns(result1 prometheus.Counter) {
	fake.kafkaConsumePausedTotalMutex.Lock()
	defer fake.kafkaConsumePausedTotalMutex.Unlock()
	fake.KafkaConsumePausedTotalStub = nil
	fake.kafkaConsumePausedTotalReturns = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) KafkaConsumePausedTotalReturnsOnCall(i int, result1 prometheus.Counter) {
	fake.kafkaConsumePausedTotalMutex.Lock()
	defer fake.kafkaConsumePausedTotalMutex.Unlock()
	fake.KafkaConsumePausedTotalStub = nil
	if fake.kafkaConsumePausedTotalReturnsOnCall == nil {
		fake.kafkaConsumePausedTotalReturnsOnCall = make(map[int]struct {
			result1 prometheus.Counter
		})
	}
	fake.kafkaConsumePausedTotalReturnsOnCall[i] = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) PlanningRetryTotal(arg1 string) prometheus.Counter {
	fake.planningRetryTotalMutex.Lock()
	ret, specificReturn := fake.planningRetryTotalReturnsOnCall[len(fake.planningRetryTotalArgsForCall)]
	fake.planningRetryTotalArgsForCall = append(fake.planningRetryTotalArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.PlanningRetryTotalStub
	fakeReturns := fake.planningRetryTotalReturns
	fake.recordInvocation("PlanningRetryTotal", []interface{}{arg1})
	fake.planningRetryTotalMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Metrics) PlanningRetryTotalCallCount() int {
	fake.planningRetryTotalMutex.RLock()
	defer fake.planningRetryTotalMutex.RUnlock()
	return len(fake.planningRetryTotalArgsForCall)
}

func (fake *Metrics) PlanningRetryTotalCalls(stub func(string) prometheus.Counter) {
	fake.planningRetryTotalMutex.Lock()
	defer fake.planningRetryTotalMutex.Unlock()
	fake.PlanningRetryTotalStub = stub
}

func (fake *Metrics) PlanningRetryTotalArgsForCall(i int) string {
	fake.planningRetryTotalMutex.RLock()
	defer fake.planningRetryTotalMutex.RUnlock()
	argsForCall := fake.planningRetryTotalArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) PlanningRetryTotalReturns(result1 prometheus.Counter) {
	fake.planningRetryTotalMutex.Lock()
	defer fake.planningRetryTotalMutex.Unlock()
	fake.PlanningRetryTotalStub = nil
	fake.planningRetryTotalReturns = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) PlanningRetryTotalReturnsOnCall(i int, result1 prometheus.Counter) {
	fake.planningRetryTotalMutex.Lock()
	defer fake.planningRetryTotalMutex.Unlock()
	fake.PlanningRetryTotalStub = nil
	if fake.planningRetryTotalReturnsOnCall == nil {
		fake.planningRetryTotalReturnsOnCall = make(map[int]struct {
			result1 prometheus.Counter
		})
	}
	fake.planningRetryTotalReturnsOnCall[i] = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) ResultsWrittenTotal(arg1 string) prometheus.Counter {
	fake.resultsWrittenTotalMutex.Lock()
	ret, specificReturn := fake.resultsWrittenTotalReturnsOnCall[len(fake.resultsWrittenTotalArgsForCall)]
	fake.resultsWrittenTotalArgsForCall = append(fake.resultsWrittenTotalArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ResultsWrittenTotalStub
	fakeReturns := fake.resultsWrittenTotalReturns
	fake.recordInvocation("ResultsWrittenTotal", []interface{}{arg1})
	fake.resultsWrittenTotalMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Metrics) ResultsWrittenTotalCallCount() int {
	fake.resultsWrittenTotalMutex.RLock()
	defer fake.resultsWrittenTotalMutex.RUnlock()
	return len(fake.resultsWrittenTotalArgsForCall)
}

func (fake *Metrics) ResultsWrittenTotalCalls(stub func(string) prometheus.Counter) {
	fake.resultsWrittenTotalMutex.Lock()
	defer fake.resultsWrittenTotalMutex.Unlock()
	fake.ResultsWrittenTotalStub = stub
}

func (fake *Metrics) ResultsWrittenTotalArgsForCall(i int) string {
	fake.resultsWrittenTotalMutex.RLock()
	defer fake.resultsWrittenTotalMutex.RUnlock()
	argsForCall := fake.resultsWrittenTotalArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) ResultsWrittenTotalReturns(result1 prometheus.Counter) {
	fake.resultsWrittenTotalMutex.Lock()
	defer fake.resultsWrittenTotalMutex.Unlock()
	fake.ResultsWrittenTotalStub = nil
	fake.resultsWrittenTotalReturns = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) ResultsWrittenTotalReturnsOnCall(i int, result1 prometheus.Counter) {
	fake.resultsWrittenTotalMutex.Lock()
	defer fake.resultsWrittenTotalMutex.Unlock()
	fake.ResultsWrittenTotalStub = nil
	if fake.resultsWrittenTotalReturnsOnCall == nil {
		fake.resultsWrittenTotalReturnsOnCall = make(map[int]struct {
			result1 prometheus.Counter
		})
	}
	fake.resultsWrittenTotalReturnsOnCall[i] = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) ScanCyclesTotal(arg1 string) prometheus.Counter {
	fake.scanCyclesTotalMutex.Lock()
	ret, specificReturn := fake.scanCyclesTotalReturnsOnCall[len(fake.scanCyclesTotalArgsForCall)]
	fake.scanCyclesTotalArgsForCall = append(fake.scanCyclesTotalArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ScanCyclesTotalStub
	fakeReturns := fake.scanCyclesTotalReturns
	fake.recordInvocation("ScanCyclesTotal", []interface{}{arg1})
	fake.scanCyclesTotalMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Metrics) ScanCyclesTotalCallCount() int {
	fake.scanCyclesTotalMutex.RLock()
	defer fake.scanCyclesTotalMutex.RUnlock()
	return len(fake.scanCyclesTotalArgsForCall)
}

func (fake *Metrics) ScanCyclesTotalCalls(stub func(string) prometheus.Counter) {
	fake.scanCyclesTotalMutex.Lock()
	defer fake.scanCyclesTotalMutex.Unlock()
	fake.ScanCyclesTotalStub = stub
}

func (fake *Metrics) ScanCyclesTotalArgsForCall(i int) string {
	fake.scanCyclesTotalMutex.RLock()
	defer fake.scanCyclesTotalMutex.RUnlock()
	argsForCall := fake.scanCyclesTotalArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) ScanCyclesTotalReturns(result1 prometheus.Counter) {
	fake.scanCyclesTotalMutex.Lock()
	defer fake.scanCyclesTotalMutex.Unlock()
	fake.ScanCyclesTotalStub = nil
	fake.scanCyclesTotalReturns = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) ScanCyclesTotalReturnsOnCall(i int, result1 prometheus.Counter) {
	fake.scanCyclesTotalMutex.Lock()
	defer fake.scanCyclesTotalMutex.Unlock()
	fake.ScanCyclesTotalStub = nil
	if fake.scanCyclesTotalReturnsOnCall == nil {
		fake.scanCyclesTotalReturnsOnCall = make(map[int]struct {
			result1 prometheus.Counter
		})
	}
	fake.scanCyclesTotalReturnsOnCall[i] = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) SkippedFilesTotal(arg1 metrics.SkipReason) prometheus.Counter {
	fake.skippedFilesTotalMutex.Lock()
	ret, specificReturn := fake.skippedFilesTotalReturnsOnCall[len(fake.skippedFilesTotalArgsForCall)]
	fake.skippedFilesTotalArgsForCall = append(fake.skippedFilesTotalArgsForCall, struct {
		arg1 metrics.SkipReason
	}{arg1})
	stub := fake.SkippedFilesTotalStub
	fakeReturns := fake.skippedFilesTotalReturns
	fake.recordInvocation("SkippedFilesTotal", []interface{}{arg1})
	fake.skippedFilesTotalMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Metrics) SkippedFilesTotalCallCount() int {
	fake.skippedFilesTotalMutex.RLock()
	defer fake.skippedFilesTotalMutex.RUnlock()
	return len(fake.skippedFilesTotalArgsForCall)
}

func (fake *Metrics) SkippedFilesTotalCalls(stub func(metrics.SkipReason) prometheus.Counter) {
	fake.skippedFilesTotalMutex.Lock()
	defer fake.skippedFilesTotalMutex.Unlock()
	fake.SkippedFilesTotalStub = stub
}

func (fake *Metrics) SkippedFilesTotalArgsForCall(i int) metrics.SkipReason {
	fake.skippedFilesTotalMutex.RLock()
	defer fake.skippedFilesTotalMutex.RUnlock()
	argsForCall := fake.skippedFilesTotalArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) SkippedFilesTotalReturns(result1 prometheus.Counter) {
	fake.skippedFilesTotalMutex.Lock()
	defer fake.skippedFilesTotalMutex.Unlock()
	fake.SkippedFilesTotalStub = nil
	fake.skippedFilesTotalReturns = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) SkippedFilesTotalReturnsOnCall(i int, result1 prometheus.Counter) {
	fake.skippedFilesTotalMutex.Lock()
	defer fake.skippedFilesTotalMutex.Unlock()
	fake.SkippedFilesTotalStub = nil
	if fake.skippedFilesTotalReturnsOnCall == nil {
		fake.skippedFilesTotalReturnsOnCall = make(map[int]struct {
			result1 prometheus.Counter
		})
	}
	fake.skippedFilesTotalReturnsOnCall[i] = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) TasksPublishedTotal(arg1 string) prometheus.Counter {
	fake.tasksPublishedTotalMutex.Lock()
	ret, specificReturn := fake.tasksPublishedTotalReturnsOnCall[len(fake.tasksPublishedTotalArgsForCall)]
	fake.tasksPublishedTotalArgsForCall = append(fake.tasksPublishedTotalArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.TasksPublishedTotalStub
	fakeReturns := fake.tasksPublishedTotalReturns
	fake.recordInvocation("TasksPublishedTotal", []interface{}{arg1})
	fake.tasksPublishedTotalMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Metrics) TasksPublishedTotalCallCount() int {
	fake.tasksPublishedTotalMutex.RLock()
	defer fake.tasksPublishedTotalMutex.RUnlock()
	return len(fake.tasksPublishedTotalArgsForCall)
}

func (fake *Metrics) TasksPublishedTotalCalls(stub func(string) prometheus.Counter) {
	fake.tasksPublishedTotalMutex.Lock()
	defer fake.tasksPublishedTotalMutex.Unlock()
	fake.TasksPublishedTotalStub = stub
}

func (fake *Metrics) TasksPublishedTotalArgsForCall(i int) string {
	fake.tasksPublishedTotalMutex.RLock()
	defer fake.tasksPublishedTotalMutex.RUnlock()
	argsForCall := fake.tasksPublishedTotalArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) TasksPublishedTotalReturns(result1 prometheus.Counter) {
	fake.tasksPublishedTotalMutex.Lock()
	defer fake.tasksPublishedTotalMutex.Unlock()
	fake.TasksPublishedTotalStub = nil
	fake.tasksPublishedTotalReturns = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) TasksPublishedTotalReturnsOnCall(i int, result1 prometheus.Counter) {
	fake.tasksPublishedTotalMutex.Lock()
	defer fake.tasksPublishedTotalMutex.Unlock()
	fake.TasksPublishedTotalStub = nil
	if fake.tasksPublishedTotalReturnsOnCall == nil {
		fake.tasksPublishedTotalReturnsOnCall = make(map[int]struct {
			result1 prometheus.Counter
		})
	}
	fake.tasksPublishedTotalReturnsOnCall[i] = struct {
		result1 prometheus.Counter
	}{result1}
}

func (fake *Metrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Metrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ metrics.Metrics = new(Metrics)
