// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent-task-controller/pkg/redrive"
)

type RedriveSweep struct {
	RunStub        func(context.Context) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 context.Context
	}
	runReturns struct {
		result1 error
	}
	runReturnsOnCall map[int]struct {
		result1 error
	}
	SweepOnceStub        func(context.Context) error
	sweepOnceMutex       sync.RWMutex
	sweepOnceArgsForCall []struct {
		arg1 context.Context
	}
	sweepOnceReturns struct {
		result1 error
	}
	sweepOnceReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *RedriveSweep) Run(arg1 context.Context) error {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RedriveSweep) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *RedriveSweep) RunCalls(stub func(context.Context) error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *RedriveSweep) RunArgsForCall(i int) context.Context {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1
}

func (fake *RedriveSweep) RunReturns(result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *RedriveSweep) RunReturnsOnCall(i int, result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *RedriveSweep) SweepOnce(arg1 context.Context) error {
	fake.sweepOnceMutex.Lock()
	ret, specificReturn := fake.sweepOnceReturnsOnCall[len(fake.sweepOnceArgsForCall)]
	fake.sweepOnceArgsForCall = append(fake.sweepOnceArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.SweepOnceStub
	fakeReturns := fake.sweepOnceReturns
	fake.recordInvocation("SweepOnce", []interface{}{arg1})
	fake.sweepOnceMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RedriveSweep) SweepOnceCallCount() int {
	fake.sweepOnceMutex.RLock()
	defer fake.sweepOnceMutex.RUnlock()
	return len(fake.sweepOnceArgsForCall)
}

func (fake *RedriveSweep) SweepOnceCalls(stub func(context.Context) error) {
	fake.sweepOnceMutex.Lock()
	defer fake.sweepOnceMutex.Unlock()
	fake.SweepOnceStub = stub
}

func (fake *RedriveSweep) SweepOnceArgsForCall(i int) context.Context {
	fake.sweepOnceMutex.RLock()
	defer fake.sweepOnceMutex.RUnlock()
	argsForCall := fake.sweepOnceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *RedriveSweep) SweepOnceReturns(result1 error) {
	fake.sweepOnceMutex.Lock()
	defer fake.sweepOnceMutex.Unlock()
	fake.SweepOnceStub = nil
	fake.sweepOnceReturns = struct {
		result1 error
	}{result1}
}

func (fake *RedriveSweep) SweepOnceReturnsOnCall(i int, result1 error) {
	fake.sweepOnceMutex.Lock()
	defer fake.sweepOnceMutex.Unlock()
	fake.SweepOnceStub = nil
	if fake.sweepOnceReturnsOnCall == nil {
		fake.sweepOnceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.sweepOnceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *RedriveSweep) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *RedriveSweep) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ redrive.RedriveSweep = new(RedriveSweep)
