// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/lib"
	"github.com/bborbe/agent-task-controller/pkg/publisher"
)

type TaskPublisher struct {
	PublishChangedStub        func(context.Context, lib.Task) error
	publishChangedMutex       sync.RWMutex
	publishChangedArgsForCall []struct {
		arg1 context.Context
		arg2 lib.Task
	}
	publishChangedReturns struct {
		result1 error
	}
	publishChangedReturnsOnCall map[int]struct {
		result1 error
	}
	PublishDeletedStub        func(context.Context, lib.TaskIdentifier) error
	publishDeletedMutex       sync.RWMutex
	publishDeletedArgsForCall []struct {
		arg1 context.Context
		arg2 lib.TaskIdentifier
	}
	publishDeletedReturns struct {
		result1 error
	}
	publishDeletedReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TaskPublisher) PublishChanged(arg1 context.Context, arg2 lib.Task) error {
	fake.publishChangedMutex.Lock()
	ret, specificReturn := fake.publishChangedReturnsOnCall[len(fake.publishChangedArgsForCall)]
	fake.publishChangedArgsForCall = append(fake.publishChangedArgsForCall, struct {
		arg1 context.Context
		arg2 lib.Task
	}{arg1, arg2})
	stub := fake.PublishChangedStub
	fakeReturns := fake.publishChangedReturns
	fake.recordInvocation("PublishChanged", []interface{}{arg1, arg2})
	fake.publishChangedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *TaskPublisher) PublishChangedCallCount() int {
	fake.publishChangedMutex.RLock()
	defer fake.publishChangedMutex.RUnlock()
	return len(fake.publishChangedArgsForCall)
}

func (fake *TaskPublisher) PublishChangedCalls(stub func(context.Context, lib.Task) error) {
	fake.publishChangedMutex.Lock()
	defer fake.publishChangedMutex.Unlock()
	fake.PublishChangedStub = stub
}

func (fake *TaskPublisher) PublishChangedArgsForCall(i int) (context.Context, lib.Task) {
	fake.publishChangedMutex.RLock()
	defer fake.publishChangedMutex.RUnlock()
	argsForCall := fake.publishChangedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *TaskPublisher) PublishChangedReturns(result1 error) {
	fake.publishChangedMutex.Lock()
	defer fake.publishChangedMutex.Unlock()
	fake.PublishChangedStub = nil
	fake.publishChangedReturns = struct {
		result1 error
	}{result1}
}

func (fake *TaskPublisher) PublishChangedReturnsOnCall(i int, result1 error) {
	fake.publishChangedMutex.Lock()
	defer fake.publishChangedMutex.Unlock()
	fake.PublishChangedStub = nil
	if fake.publishChangedReturnsOnCall == nil {
		fake.publishChangedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.publishChangedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *TaskPublisher) PublishDeleted(arg1 context.Context, arg2 lib.TaskIdentifier) error {
	fake.publishDeletedMutex.Lock()
	ret, specificReturn := fake.publishDeletedReturnsOnCall[len(fake.publishDeletedArgsForCall)]
	fake.publishDeletedArgsForCall = append(fake.publishDeletedArgsForCall, struct {
		arg1 context.Context
		arg2 lib.TaskIdentifier
	}{arg1, arg2})
	stub := fake.PublishDeletedStub
	fakeReturns := fake.publishDeletedReturns
	fake.recordInvocation("PublishDeleted", []interface{}{arg1, arg2})
	fake.publishDeletedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *TaskPublisher) PublishDeletedCallCount() int {
	fake.publishDeletedMutex.RLock()
	defer fake.publishDeletedMutex.RUnlock()
	return len(fake.publishDeletedArgsForCall)
}

func (fake *TaskPublisher) PublishDeletedCalls(stub func(context.Context, lib.TaskIdentifier) error) {
	fake.publishDeletedMutex.Lock()
	defer fake.publishDeletedMutex.Unlock()
	fake.PublishDeletedStub = stub
}

func (fake *TaskPublisher) PublishDeletedArgsForCall(i int) (context.Context, lib.TaskIdentifier) {
	fake.publishDeletedMutex.RLock()
	defer fake.publishDeletedMutex.RUnlock()
	argsForCall := fake.publishDeletedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *TaskPublisher) PublishDeletedReturns(result1 error) {
	fake.publishDeletedMutex.Lock()
	defer fake.publishDeletedMutex.Unlock()
	fake.PublishDeletedStub = nil
	fake.publishDeletedReturns = struct {
		result1 error
	}{result1}
}

func (fake *TaskPublisher) PublishDeletedReturnsOnCall(i int, result1 error) {
	fake.publishDeletedMutex.Lock()
	defer fake.publishDeletedMutex.Unlock()
	fake.PublishDeletedStub = nil
	if fake.publishDeletedReturnsOnCall == nil {
		fake.publishDeletedReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.publishDeletedReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *TaskPublisher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TaskPublisher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ publisher.TaskPublisher = new(TaskPublisher)
