// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	lib "github.com/bborbe/agent"
	"github.com/bborbe/agent-task-controller/pkg/scanner"
)

type VaultScanner struct {
	ResolveStub        func(context.Context, lib.TaskIdentifier) (string, bool, error)
	resolveMutex       sync.RWMutex
	resolveArgsForCall []struct {
		arg1 context.Context
		arg2 lib.TaskIdentifier
	}
	resolveReturns struct {
		result1 string
		result2 bool
		result3 error
	}
	resolveReturnsOnCall map[int]struct {
		result1 string
		result2 bool
		result3 error
	}
	RunStub        func(context.Context, chan<- scanner.ScanResult) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 context.Context
		arg2 chan<- scanner.ScanResult
	}
	runReturns struct {
		result1 error
	}
	runReturnsOnCall map[int]struct {
		result1 error
	}
	RunCycleStub        func(context.Context, chan<- scanner.ScanResult)
	runCycleMutex       sync.RWMutex
	runCycleArgsForCall []struct {
		arg1 context.Context
		arg2 chan<- scanner.ScanResult
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *VaultScanner) Resolve(arg1 context.Context, arg2 lib.TaskIdentifier) (string, bool, error) {
	fake.resolveMutex.Lock()
	ret, specificReturn := fake.resolveReturnsOnCall[len(fake.resolveArgsForCall)]
	fake.resolveArgsForCall = append(fake.resolveArgsForCall, struct {
		arg1 context.Context
		arg2 lib.TaskIdentifier
	}{arg1, arg2})
	stub := fake.ResolveStub
	fakeReturns := fake.resolveReturns
	fake.recordInvocation("Resolve", []interface{}{arg1, arg2})
	fake.resolveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *VaultScanner) ResolveCallCount() int {
	fake.resolveMutex.RLock()
	defer fake.resolveMutex.RUnlock()
	return len(fake.resolveArgsForCall)
}

func (fake *VaultScanner) ResolveCalls(stub func(context.Context, lib.TaskIdentifier) (string, bool, error)) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = stub
}

func (fake *VaultScanner) ResolveArgsForCall(i int) (context.Context, lib.TaskIdentifier) {
	fake.resolveMutex.RLock()
	defer fake.resolveMutex.RUnlock()
	argsForCall := fake.resolveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *VaultScanner) ResolveReturns(result1 string, result2 bool, result3 error) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = nil
	fake.resolveReturns = struct {
		result1 string
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *VaultScanner) ResolveReturnsOnCall(i int, result1 string, result2 bool, result3 error) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = nil
	if fake.resolveReturnsOnCall == nil {
		fake.resolveReturnsOnCall = make(map[int]struct {
			result1 string
			result2 bool
			result3 error
		})
	}
	fake.resolveReturnsOnCall[i] = struct {
		result1 string
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *VaultScanner) Run(arg1 context.Context, arg2 chan<- scanner.ScanResult) error {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 context.Context
		arg2 chan<- scanner.ScanResult
	}{arg1, arg2})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1, arg2})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *VaultScanner) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *VaultScanner) RunCalls(stub func(context.Context, chan<- scanner.ScanResult) error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *VaultScanner) RunArgsForCall(i int) (context.Context, chan<- scanner.ScanResult) {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *VaultScanner) RunReturns(result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *VaultScanner) RunReturnsOnCall(i int, result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *VaultScanner) RunCycle(arg1 context.Context, arg2 chan<- scanner.ScanResult) {
	fake.runCycleMutex.Lock()
	fake.runCycleArgsForCall = append(fake.runCycleArgsForCall, struct {
		arg1 context.Context
		arg2 chan<- scanner.ScanResult
	}{arg1, arg2})
	stub := fake.RunCycleStub
	fake.recordInvocation("RunCycle", []interface{}{arg1, arg2})
	fake.runCycleMutex.Unlock()
	if stub != nil {
		fake.RunCycleStub(arg1, arg2)
	}
}

func (fake *VaultScanner) RunCycleCallCount() int {
	fake.runCycleMutex.RLock()
	defer fake.runCycleMutex.RUnlock()
	return len(fake.runCycleArgsForCall)
}

func (fake *VaultScanner) RunCycleCalls(stub func(context.Context, chan<- scanner.ScanResult)) {
	fake.runCycleMutex.Lock()
	defer fake.runCycleMutex.Unlock()
	fake.RunCycleStub = stub
}

func (fake *VaultScanner) RunCycleArgsForCall(i int) (context.Context, chan<- scanner.ScanResult) {
	fake.runCycleMutex.RLock()
	defer fake.runCycleMutex.RUnlock()
	argsForCall := fake.runCycleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *VaultScanner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *VaultScanner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ scanner.VaultScanner = new(VaultScanner)
